### ISSUE TITLE
Bug with    "fixed_top_menu"

### ISSUE THREAD

**Issue by DSMejantel** [sqlpage/SQLPage#588]
### Introduction
  When  "fixed_top_menu":"TRUE" is actived, the page is not correctly done since sqlpage 0.27.

### To Reproduce

```sql
--Menu
SELECT 'dynamic' AS component, 
CASE WHEN $group_id=1
THEN sqlpage.read_file_as_text('index.json')
ELSE sqlpage.read_file_as_text('menu.json')
            END    AS properties; 

select 
    'button' as component,
    'sm'     as size,
    --'pill'   as shape,
    'center' as justify;
select 
    'AESH' as title,
    'etab_aesh.sql?id=' || $id as link,
```

### Screenshots
![probleme_menu](https://github.com/user-attachments/assets/15b0f43f-cb4d-415a-83ca-a84959b854ef)

**Comment by lovasoa** [comment]
Hello @DSMejantel and welcome back :smiley: !
  This should be fixed in v0.29 (not released yet). Can you test it ? It's available on docker under `lovasoa/sqlpage:main`. If you don't have docker, i'm joining a linux binary.

**Comment by lovasoa** [comment]
[sqlpage-v0.29-preview.zip](https://github.com/user-attachments/files/16999470/sqlpage-v0.29-preview.zip)

**Comment by lovasoa** [comment]
Closing this as fixed :)
