### ISSUE TITLE
[feat] Columns Component - Markdown support for `item`'s description

### ISSUE THREAD

**Issue by accforgithubtest** [sqlpage/SQLPage#646]
Currently in columns component, `description_md` is only supported for `description` under the `value`.

It will be great if there is markdown support for all the `item` as well, allowing for hyperlinks and text formatting as well.

A potential solution would look like -

```sql
JSON_OBJECT("icon", "check", "color", "green", "description_md", "[Collaboration Tools](https://collabtools.local)")
```

**Comment by lovasoa** [comment]
I implemented this, it'll be in v0.31
