### ISSUE TITLE
did 0.29.0 release get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [sqlpage/SQLPage#648]
👋 seeing some checksum changed while regression build the 0.29.0 release, raise this issue to confirm if there was some re-tagging? Thanks!

error log https://github.com/Homebrew/homebrew-core/actions/runs/11393912950/job/31705951453?pr=194802#step:3:13326

relates to https://github.com/Homebrew/homebrew-core/pull/194802

**Comment by lovasoa** [comment]
Hello ! Yes, I'm sorry, I made a mistake when tagging v0.29, and I re-tagged it 4 minutes later, thinking no one would have picked it up so fast. But apparently homebrew was faster than me...

**Comment by chenrui333** [comment]
no worries, thanks for confirming the re-tagging. <3
