### ISSUE TITLE
Sorting data in table component

### ISSUE THREAD

**Issue by DSMejantel** [sqlpage/SQLPage#660]
### Introduction

Since 0.30, Sorting data from table component don't work on the most of my page. 

### To Reproduce
Il tried with Firefox ans Chrome on computer or smartphone and two différents applications. 

### Version information

 - OS: Ubuntu 22.04
 - Database e.g. SQLite,
 - SQLPage Version 0.30

**Comment by DSMejantel** [comment]
Sorting data is possible only when we have 'TRUE as search' in the top level parameters. Before in sqlpage 0.29 'TRUE as sort' was only necessary.

**Comment by lovasoa** [comment]
Thank you for the quick report, @DSMejantel !

I'm releasing v0.30.1 with a fix for this issue.

I also added tests to prevent other regressions in this area in the future.
