### ISSUE TITLE
MSSQL: Data of type `varchar` disappears when the database server character encoding is chinese

### ISSUE THREAD

**Issue by BlueHtml** [sqlpage/SQLPage#662]
### Introduction

Hello, in MSSQL, when the field type is `varchar`, its value disappears. This issue occurs with both the CSV component and the JSON component.

#### JSON Component

The SQL is as follows:
```sql
select 'json' AS component, 'array' AS type;

select top 2 * from [Ban].[dbo].[ErrorLog];
select 'INFO' as LogLevel;
select CAST('INFO' as varchar(100)) as LogLevel;
```

The MSSQL execution result is as follows:
![image](https://github.com/user-attachments/assets/671933a2-982e-4ec9-844f-92fa26581024)

The JSON component execution result is as follows (**The values of `LogLevel` and `LogSource` are missing**):
```json
[
{"ID":1,"LogTime":"2023-01-31T08:26:25.573+00:00","LogLevel":"","LogSource":"","Message":"默认数量:minWorker:4,minIOC:1;设置:300","Exception":""},
{"ID":2,"LogTime":"2023-01-31T08:26:26.100+00:00","LogLevel":"","LogSource":"","Message":"conf加载成功","Exception":""},
{"LogLevel":"INFO"},
{"LogLevel":""}
]
```

#### CSV Component

The SQL is as follows:
```sql
select 
    'csv'              as component,
    'Download my data' as title,
    'people'           as filename,
    'file-download'    as icon,
    'green'            as color,
    TRUE               as bom;

select top 2 * from [Ban].[dbo].[ErrorLog];
select 'INFO' as LogLevel;
select CAST('INFO' as varchar(100)) as LogLevel;
```

The MSSQL execution result is as follows:
![image](https://github.com/user-attachments/assets/671933a2-982e-4ec9-844f-92fa26581024)

The CSV component execution result is as follows (**The values of `LogLevel` and `LogSource` are missing**):
```csv
ID,LogTime,LogLevel,LogSource,Message,Exception
1,2023-01-31T08:26:25.573+00:00,,,"默认数量:minWorker:4,minIOC:1;设置:300",
2,2023-01-31T08:26:26.100+00:00,,,conf加载成功,
,,INFO,,,
,,,,,
```

The MSSQL table creation statement and data types are as follows:
```sql
CREATE TABLE [dbo].[ErrorLog](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[LogTime] [datetime] NOT NULL,
	[LogLevel] [varchar](100) NOT NULL,
	[LogSource] [varchar](200) NOT NULL,
	[Message] nvarchar(MAX) NOT NULL,
	[Exception] nvarchar(MAX) NOT NULL,
)
```

### Version information

 - OS: `windowns 10 Simplified Chinese zh-CN`
 - Database: `MSSQL`
 - SQLPage Version: `v0.30.0`

**Comment by lovasoa** [comment]
Thanks for reporting this issue ! I'll look into it.

**Comment by lovasoa** [comment]
Hi ! I tried looking into it, but I cannot reproduce your issue

![image](https://github.com/user-attachments/assets/6e12fc8b-1826-45ac-bc64-e045fdf27fff)

**Comment by lovasoa** [comment]
I think I found the root cause. Our SQL Server driver did not support databases with character encodings other than WINDOWS-1252. I pushed a fix ! 

Could you please try it and confirm the problem is solved ? Here is a development build: https://we.tl/t-vKlx1UMhdW

**Comment by BlueHtml** [comment]
@lovasoa The execution result of this development version is normal.
![image](https://github.com/user-attachments/assets/8b58a4ed-c858-43e3-96e6-77fb4dace316)

**Comment by lovasoa** [comment]
Great !

**Comment by lovasoa** [comment]
Does it also work with chinese characters ?

**Comment by BlueHtml** [comment]
> Does it also work with chinese characters ?

@lovasoa Yes

**Comment by BlueHtml** [comment]
@lovasoa However, a new issue has arisen: the value of the `bit` type is incorrect.
```sql
select top 2 * from [ZrAdmin].[dbo].[sys_role];;
select 'test测试' as LogLevel;
select CAST('test测试' as varchar(100)) as LogLevel;

select CAST(1 as bit) as menu_check_strictly;
select CAST(0 as bit) as menu_check_strictly;
```

![image](https://github.com/user-attachments/assets/a301e948-3547-42cf-82bd-6119756e67fc)
![image](https://github.com/user-attachments/assets/5b00a88a-a326-4fb5-bb94-b43960ec4319)
![image](https://github.com/user-attachments/assets/9da92106-f6fa-4386-83a0-229ac73d5a4f)
![image](https://github.com/user-attachments/assets/db61ef0b-ab25-4bba-83cb-97945bdfad71)
