### ISSUE TITLE
CSV Export adds an empty column

### ISSUE THREAD

**Issue by nofue** [sqlpage/SQLPage#663]
### Introduction

After export, there's a column added to the table. 

### To Reproduce

Just export a table using the CSV component. 

```sql
select  'dynamic' as component
      , sqlpage.run_sql('tp_sh.sql') as properties;

select  'text' as component
      , 'Download ' || $ab || ' - ' || $bis as title
      , 'Durch Klick auf den Button wird das Tagesprotokoll in das im Browser eingestellte Download-Verzeichnis geladen.' as contents
      ;
      
SELECT
    'csv'              as component,
    'CSV Download'     as title,
    'tagesprotokoll-' || $ab || '-' || $bis  as filename,
    'file-download'    as icon,
    'primary'          as color,
    ','                as separator,
    TRUE               as bom;

        
SELECT 
  CONCAT (schlafvon, ' ', schlafvonzeit) AS 'Schlaf Anfang',
  CONCAT (schlafbis, ' ', schlafbiszeit) AS 'Schlaf Ende',
  qualitaet     AS 'Sch Qu',
  plan          AS 'Plan',
  gewichtmrg    AS 'Gewicht morgens',
  gewichtabd    AS 'Gewicht abends',
  siesta        AS  'Siesta',
  physisch      AS 'P',
  mental        AS 'M',
  hunger        AS 'Hunger',
  energie       AS 'Energie',
  snckvrm       AS 'S1',
  sncknch       AS 'S2',
  snckabd       AS 'S3',
  haselnuss     AS 'Nüsse'
FROM protocol 
WHERE schlafvon BETWEEN $ab AND $bis
ORDER BY schlafvon ASC;

```

### Actual behavior

The fiel gets written, but opened with a stupid editor like BBEdit, there's an additional comma at the end of the line, which causes an added column. 

### Screenshots

![Bildschirmfoto 2024-11-01 um 07 31 01](https://github.com/user-attachments/assets/36b000a9-58c4-40a5-9833-0a9faaea835b)

The character after the final comma in the screenshot is the line break character ('\n').

### Expected behavior
There shouldn't be a comma after the last column of a row.

### Version information

 - OS: MacOS 11.7.10 (20G1427)
 - Database SQLite
 - SQLPage Version v0.28.0

### Additional context
I'm not sure, but I think according to the "standard" (CSV, I know), Date/Time columns should be considered text, i.e. enclosed with "" -- at least apostrophes never hurt in my experience. 

![Bildschirmfoto 2024-11-01 um 07 40 11](https://github.com/user-attachments/assets/13f10f90-4741-44bf-b462-42c1c87ca2ef)

**Comment by lovasoa** [comment]
Hello ! This issue was fixed in the latest version of SQLPage. Upgrade to SQLPage v0.30 and the empty column will disappear.

**Comment by lovasoa** [comment]
In CSV, there is no notion of "text" or "number" columns. Quotes are used when a cell contains special characters. In your case, they are not needed. If you encounter a software that fails to read that CSV, you should report the issue to them ;)

**Comment by nofue** [comment]
I know – but it never hurt to have apostrophes around strings holding spaces ;)

**Comment by lovasoa** [comment]
Actually, it hurts file sizes. Especially in the inline version of the csv component, where the entire file has to be encoded as a data URL. An unquoted space in a CSV should never be a problem. Do you have a concrete example of a program that does not handle it correctly ?

**Comment by nofue** [comment]
It's getting academic -- my log worth one month of datetime values will suffer from gaining 64 bytes ;) And no, currently I don't see any issues with csv files, but I remember dealing with lots of issues since 1984, when I began coding. At 64 bytes per month I wouldn't just take the risk of eventually having to deal with a program which insists in apostrophes. I I also remember dealing with a nasty import with some cms module only a couple of years ago -- to me it's just a waste of time to even think about this issue. You may be right, but there will always be a big IF which in my experience always hits when you need it the least. I also wonder how much of  difference with an inline CSV apostrophes will make… In my case, "your" CSV and is 6.4% "lighter" than another one created with a different application. Or 235 bytes. This post has 867 bytes already ;)
