### ISSUE TITLE
Values of type `bit` are decoded as strings instead of booleans in Microsoft SQL server

### ISSUE THREAD

**Issue by lovasoa** [sqlpage/SQLPage#666]
@lovasoa However, a new issue has arisen: the value of the `bit` type is incorrect.
```sql
select top 2 * from [ZrAdmin].[dbo].[sys_role];;
select 'test测试' as LogLevel;
select CAST('test测试' as varchar(100)) as LogLevel;

select CAST(1 as bit) as menu_check_strictly;
select CAST(0 as bit) as menu_check_strictly;
```

![image](https://github.com/user-attachments/assets/a301e948-3547-42cf-82bd-6119756e67fc)
![image](https://github.com/user-attachments/assets/5b00a88a-a326-4fb5-bb94-b43960ec4319)
![image](https://github.com/user-attachments/assets/9da92106-f6fa-4386-83a0-229ac73d5a4f)
![image](https://github.com/user-attachments/assets/db61ef0b-ab25-4bba-83cb-97945bdfad71)

_Originally posted by @BlueHtml in https://github.com/sqlpage/SQLPage/issues/662#issuecomment-2452905163_

**Comment by lovasoa** [comment]
@BlueHtml , I fixed this too. Here is a new preview build: https://we.tl/t-F9BvjGElcQ

**Comment by BlueHtml** [comment]
@lovasoa The execution result of this preview build is normal.
![image](https://github.com/user-attachments/assets/75b24fb6-f198-4f54-a759-d58f949d4b00)
