### ISSUE TITLE
mariadb smallint / table component

### ISSUE THREAD

**Issue by aedion-a** [sqlpage/SQLPage#678]
### Introduction

On MariaDB, smallint column are not decoded as number in table component (with sort and search options enabled).

I use cast(fieldxxx as int) as workaround.

### To Reproduce

On component table, I see

- ">" (instead of value 62 in DB)
- "" (instead of 30)
- "2" (instead of 50)

### Version information

 - OS: Linux
 - Database : Mariadb 10.5.20
 - SQLPage Version 0.30

**Comment by lovasoa** [comment]
Hello ! This should be fixed in the latest development version ! Support for multiple less common mysql and mssql datatypes has been added to.

Could you please test and confirm everything works for you ? The latest development version can be used from docker, under `lovasoa/sqlpage:main`

**Comment by aedion-a** [comment]
Hello,
thanks for your answer.

I have try with "cargo build --release" on current version of main branch ("SQLPage v0.31.0 started successfully") and I observe the same issue.
The column is  smallint(4), UNSIGNED. I try SQL request on table and on view and I notice the same behavior.
And I have no migration.

**Comment by lovasoa** [comment]
Ok, now it's fixed for good; sorry !

![image](https://github.com/user-attachments/assets/5f1d5937-b913-430e-9e17-df814b6d3304)
