### ISSUE TITLE
Big number change percent doens't show if no description

### ISSUE THREAD

**Issue by ToniJ123** [sqlpage/SQLPage#688]
### Introduction

Big number change percent doens't show if no description

### To Reproduce

```sql
select 
    'big_number'          as component,
    6                     as columns,
    'colorfull_dashboard' as id;
select 
    'Vahvuus tällä viikolla' as title,
    87                as value,
    '%'               as unit,
    2                 as change_percent,
    87                as progress_percent,
    ' '             as description,
    'blue'            as progress_color,
    'cyan'   as color;

/*
--Not working solution at the moment
select 
    'big_number'          as component,
    6                     as columns,
    'colorfull_dashboard' as id;
select 
    'Vahvuus tällä viikolla' as title,
    87                as value,
    '%'               as unit,
    2                 as change_percent,
    87                as progress_percent,
    'blue'            as progress_color,
    'cyan'   as color;
*/
```

### Actual behavior

If big number component doesn't have description defined, it will not render change percent, even
it would be defined

```
your error message here
```

### Screenshots

![bignumberbug](https://github.com/user-attachments/assets/8befe836-0324-4a98-bd0e-3c6300217424)

### Expected behavior

I suppose that change percent could be presented without description as well

### Version information

Doesn't matter

### Additional context
Simple as that

**Comment by lovasoa** [comment]
fixed in 0.31!

**Comment by ToniJ123** [comment]
Hi, great that this is fixed now, but is the behaviour of the big number elements still like it should be? Here is an example when the size differs pretty much depending what parameters are used, and one in the middle is now without description field?
Also when using all the parameters, it goes straight attached to the next row's big number elements? Is this the intented behaviour?

![big_number_layout](https://github.com/user-attachments/assets/3e84bd1d-6830-4c9b-9009-be1d09d6b223)


Thanks! Keep up the good work! 👍

**Comment by lovasoa** [comment]
Hi Toni ! Thanks for the feedback ! Can you open separate issues, with a minimal reproduction for each one, to help us track this ?
