### ISSUE TITLE
official website error on high load 

### ISSUE THREAD

**Issue by Ridten** [sqlpage/SQLPage#713]
Opening main page welcomed with next error message:

In "index.sql": The following error occurred while executing an SQL statement:
error returned from database: (code: 1) no such table: example

The SQL statement sent by SQLPage was:
SELECT 'dynamic' AS component, properties FROM example WHERE component = 'shell' LIMIT 1;

![image](https://github.com/user-attachments/assets/803bd847-c77c-4bd0-88e1-2459c7f27082)

The documentation page also gives an error:

In "documentation.sql": The following error occurred while executing an SQL statement:
error returned from database: (code: 1) no such table: example

The SQL statement sent by SQLPage was:
SELECT 'dynamic' AS component, json_patch(json_extract(properties, '$[0]'), json_object('title', coalesce(CAST(? AS TEXT) || ' - ', '') || 'SQLPage Documentation')) AS properties FROM example WHERE component = 'shell' LIMIT 1;

![image](https://github.com/user-attachments/assets/f5969a77-51e9-478c-a867-40a4ebde05a6)

Browser: Tor 14.0.2

**Comment by Ridten** [comment]
Now evrything works fine

**Comment by lovasoa** [comment]
I'm leaving this opened until we pinpoint and fix the underlying issue.
