### ISSUE TITLE
Form reset button for select (multiple) dropdown type doesn't work still

### ISSUE THREAD

**Issue by ToniJ123** [sqlpage/SQLPage#719]
### Introduction

Form reset button for select (multiple) dropdown type doesn't work still

### To Reproduce

List of steps to reproduce the behavior. Include the sql file you are using and the eventual relevant parts of your database schema

```sql
-- query options from database
```

### Actual behavior

Even though this wasn't in the 0.31.0 change list as fixed, but heard other way that it should be fixed in this version.
It isn't.

**When you now click the reset button, it just opens all the dropdown menus?**

```
Below in screenshots what happens
```

### Screenshots

![reset_wont_work_still1](https://github.com/user-attachments/assets/9a7f4f08-e460-4b66-83d1-fdea0bdba7e9)

![reset_wont_work_still2](https://github.com/user-attachments/assets/711abcd2-e854-47fe-bf63-61694a5a0061)

### Expected behavior
Reset button should reset it back to the original state / default values / empty values

### Version information

Anything

### Additional context
-

**Comment by MrBarnacle** [comment]
I had the same problem too, with the new update. I came back to the previous version ( SQLPage v0.30.1 ) and the problem disappeared.

**Comment by lovasoa** [comment]
Oh, I see. You mean that it does reset all the form fields correctly, but **also** opens the dropdowns, and this is undesirable ?

**Comment by lovasoa** [comment]
I fixed the problem ! The fix be in the next release

**Comment by ToniJ123** [comment]
Yeah reset button didn't clear form fields (multiple dropdown) and opened the dropdowns, so there were two things wrong.

**Comment by ToniJ123** [comment]
Okay more information to this now, when you send the form, and in our case selected data goes to url variables, after that this issue begins. When you just come to the page and do selects to the multiselect dropdowns, and reset, it works. But after you come to the page with those multiselect dropdown values set by url variables, this reset isn't working.

Hope this extra information helps finding the issue.

**Comment by lovasoa** [comment]
Reset is not supposed to clear the form fields, it resets them to their initial value.

But opening the drop-downs was a bug, which is now fixed.

**Comment by MrBarnacle** [comment]
> Oh, I see. You mean that it does reset all the form fields correctly, but **also** opens the dropdowns, and this is undesirable ?

I noticed that the dropdowns stayed open and I thought it was a bug. I didn't investigate further... 
Thank you very much for your fast reply and your effort to resolve the problem.

**Comment by ToniJ123** [comment]
> Reset is not supposed to clear the form fields, it resets them to their initial value.
> 
> But opening the drop-downs was a bug, which is now fixed.

Yeah our initial values update when we click send form, as we add them to the url as variables like www.url.com?this=1&that=2 and we read (while returning to the same site) those as selected values to the multiselect dropdown fields, then we cannot get rid of them as they are the initial values. So in our case at least, there should be something like "clear" button for just clearing the values to their default state.

Our default state changes everytime we change selected data in those fields and we refresh the site by sending the form, making this reset button as it's current method, useless, as you can only remove those objects, which you have added to multiselect dropdown fields, in current session in the page.

Meaning in example 5, we would this reset, or optionally clear button, to clean field totally, which it doesn't, because it cannot "overwrite" the selected values.

**Comment by lovasoa** [comment]
Toni, I think your "clear" button should actually be a link that removes the URL parameters.

**Comment by ToniJ123** [comment]
Perhaps that would be the best case, but could we somehow have it inside the form? As an external one button somewhere on the page just consumes much space for just one single button, and makes it look messy, as this buttons functionaly straigthly in our case affects to the form (fields) only. It would make sense to be able to have that button inside form. But of course we realise that this kind of custom button inside the form is pretty much of work to be done for just specific cases where form's original use-case is not enough.
