### ISSUE TITLE
Sorting of Table Component Works Once when there are spaces in column names

### ISSUE THREAD

**Issue by nosbig** [sqlpage/SQLPage#724]
### Introduction

Working through the examples on learnsqlpage.com, I attempted to sort the table from the table_example.sql.  Clicking on any of the three headers, I can sort any one column once.  However, no amount of additional clicks on any column in the table re-sorts the table.

### To Reproduce

Use the default table_example.sql from the LearnSQLPage site, included below.  Click on the First Name column and watch the column sort in reverse.  Once the table is sorted, it will not re-sort in that column or any other column.

```sql
SELECT 
    'table'               AS component, 
    'Static Data Table'   AS title, 
    TRUE                  AS sort, 
    TRUE                  AS search;
SELECT 
    'Alice'               AS 'First Name', 
    'Smith'               AS 'Last Name',
    'alice@example.com'   AS 'Email'
SELECT  
    'Bob', 
    'Jones', 
    'bob@example.com';
```

### Actual behavior

The output table will sort any column once but will not sort again.

### Version information

 - OS: Linux
 - Database [e.g. SQLite, Postgres]: N/A, default examples
 - SQLPage Version [found when hovering the default footer of pages]: 0.31.0

**Comment by nosbig** [comment]
I performed some additional tests with the new information this morning, and here's what I found:
* Original Example: Failed
* Add Column Names (with spaces) to the second clause: Passed
* Add UNION ALL between the clauses without added column names: Passed
* Add Column Names (with both clauses using underscores) to the second clause (no UNION ALL): Passed
* 1st clause with underscore, 2nd clause without column names, no UNION ALL: Failed
* 1st clause with spaces, 2nd clause without column names, no UNION ALL: Failed

So, it looks like to me that spaces aren't the issue, but the fact that if you don't have column names defined on all clauses OR a UNION ALL to bind all results into a cohesive single result set, the sorting doesn't know how to properly handle the scenario.

So, I don't think this is really a bug with the code, now, but a documentation issue (at least with the example on learnsqlpage.com, section 4.4 for the table component) which includes valid SQL but a syntactically incorrect query for feeding into the table component.  As far as I can tell, every example in the main documentation for the component (https://sql-page.com/component.sql?component=table) does appear to have all clauses with column names in all examples and no indication that not having them would cause issues.  I wonder if there was a default in the past to allow subsequent queries against a single dataset (or static values) with the same number of columns to "reuse" the previous column layout and merge the results and this default was changed in subsequent versions.

**Comment by lovasoa** [comment]
I'll ask Nick from [learnsqlpage.com](https://learnsqlpage.com) if he can update his tutorial :)

>  I wonder if there was a default in the past to allow subsequent queries against a single dataset 

This has always worked, but was never documented or tested against...
