### ISSUE TITLE
Form / error or cast with number / mariadb

### ISSUE THREAD

**Issue by aedion-a** [sqlpage/SQLPage#725]
### Introduction

Unable to record number field in MariaDB when the value is empty.

### To Reproduce

```sql
CREATE OR REPLACE TABLE test (
	id INT NULL AUTO_INCREMENT,
	score INT NULL,
        primary key(id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;
```

```sql
-- test.sql
SELECT
   'form'                       as component,
   'test'                         as title,
   'save_test.sql'         as action,
   'déclarer'                 as validate,
   'réinitialiser'            as reset;

SELECT
       'score'             AS name,
       'score'             AS label,
       'number'            AS type,
       1                   AS min,
       1                   AS step;
```

```sql
-- save_test.sql
INSERT INTO test (score)  values (:score);

RETURNING 'redirect' AS component, 'index.sql' AS link
```

### Actual behavior

Don't enter anything, just validate and the error occurs

```
In "save_test.sql": The following error occurred while executing an SQL statement:
error returned from database: 1366 (22007): Incorrect integer value: '' for column `test`.`score` at row 1

The SQL statement sent by SQLPage was:
INSERT INTO test (score) VALUES (CAST(? AS CHAR));
```

### Expected behavior

The value "NULL" should have been saved.

### Version information

 - OS: Xubuntu
 - Database : MariaDB 10.3
 - SQLPage Version : 0.31.0

**Comment by lovasoa** [comment]
Hello and thank you for the report !

I think what you are looking for is the [`NULLIF`](https://mariadb.com/kb/en/nullif/) SQL function:

```sql
INSERT INTO test (score)  values (NULLIF(:score, ''));
```

SQLPage is properly following the value passed to the page. `:score` will be NULL if no `score` variable was posted to the page. However, if an empty string was passed, you will be able to access it from your code as-is. You can then use your database's standard functions to handle each case the way you need. Here, you can convert the empty string to a null using the NULLIF function.

**Comment by aedion-a** [comment]
Thank you for this solution.
