### ISSUE TITLE
Invalid link to the docker image on website

### ISSUE THREAD

**Issue by kspeeckaert** [sqlpage/SQLPage#734]
### Introduction

The page [https://sql-page.com/your-first-sql-website/](https://sql-page.com/your-first-sql-website/) contains an erroneous link to the docker image: https://hub.docker.com/repository/docker/sqlpage/SQLPage/general (which 404's) instead of [https://hub.docker.com/r/lovasoa/sqlpage](https://hub.docker.com/r/lovasoa/sqlpage).

### Screenshots

![image](https://github.com/user-attachments/assets/0de0b3ae-aa25-4787-83f6-51a381e7f308)

**Comment by lovasoa** [comment]
fixed :)
