### ISSUE TITLE
v0.31.0 - Component "card" is displayed incorrectly

### ISSUE THREAD

**Issue by Floflobel** [sqlpage/SQLPage#743]
### Introduction

I have a component card that doesn't display very well in the latest version v0.31.0. I have rollback to v0.30.1 for the moment.

### To Reproduce

```sql
select 
    'card'                 as component,
    2                      as columns;
select 
    'Information'         as title,
    'settings'             as icon,
    'green'                as color,
    '/sftp_detail_properties.sql?_sqlpage_embed&name=' || $name as embed;
select 
    'Statistics'           as title,
    'chart-dots-2'         as icon,
    'orange'               as color,
    '/sftp_detail_statistics.sql?_sqlpage_embed&name=' || $name as embed;
```

### Screenshots
v0.31.0:
![Screenshot from 2024-12-19 15-37-14](https://github.com/user-attachments/assets/0a7a786e-c8d6-49ed-a99d-e8c16407ba13)

v0.30.1:
![Screenshot from 2024-12-19 15-37-44](https://github.com/user-attachments/assets/277fd5a7-e169-4c4c-97fb-94a92273f696)

### Version information

 - OS: Debian 12
 - Database [e.g. SQLite, Postgres] Postgres
 - SQLPage Version [found when hovering the default footer of pages]: 0.31.0

**Comment by lovasoa** [comment]
Hi !
 v0.31 removed borders from cards that have embedded contents.
 
  We should probably remove the border around embedded contents only when there is not title or description in the card.
  You can overwrite `sqlpage/templates/card.handlebars` locally if this is blocking you from upgrading to v0.31.

  Do you think you could also open a pull request against https://github.com/sqlpage/SQLPage/blob/main/sqlpage/templates/card.handlebars#L29 ?
