### ISSUE TITLE
OIDC authentication

### ISSUE THREAD

**Issue by lovasoa** [sqlpage/SQLPage#82]
Feature Request: implement signin using an external OIDC (oauth) povider such as Google, Microsoft, Apple, Auth0, keycloak...

keyword: SSO, single-sign-on

This is a follow-up on https://github.com/lovasoa/SQLpage/issues/12

**Comment by lovasoa** [comment]
OIDC is still not available natively, but since sqlpage.fetch is available, it is possible to implement it manually in SQLPage. I wrote a demo here: https://github.com/lovasoa/SQLpage/tree/main/examples/single%20sign%20on%20with%20openid%20connect

**Comment by accforgithubtest** [comment]
If I have an LDAP solution ([LLDAP](https://github.com/lldap/lldap)) and SSO ([Authelia](https://github.com/authelia/authelia)) running, using a reverse proxy that is doing forward_auth, is it possible for me to capture the headers that the reverse proxy sends after authentication is successfully completed ?

I tried to capture the headers `Remote-User, Remote-Groups, Remote-Name, Remote-Email` by adding below sample to `index.sql` (of an already working sqlpage set up, but without any authentication)
```sql
select 'cookie' as component,
	'userEmail' as name,
	coalesce(sqlpage.header('Remote-Email'), '') as value;
```

But this doesn't seem to capture the information from the headers.
Can you pls guide / provide hints as to how I might be able to proceed ?

My current state is that LLDAP, Authelia are set up and working. 
SQLPage has been working without any login/auth using caddy reverse proxy.

[Apologies if I am missing something simple, I am not a developer but just learning docker based set up for self-hosting as I go along]

**Comment by lovasoa** [comment]
Hi @accforgithubtest ! I think your problem comes from capitalizing the headers. `sqlpage.header` currently expects lower-case headers:

![image](https://github.com/user-attachments/assets/ba2d49bb-a9c9-47aa-be02-7aa9d5654fc5)

**Comment by accforgithubtest** [comment]
thanks for the reply @lovasoa !

Is there any specific reason sqlpage expects them to be lower case ? 
Can this be enhanced to be case insensitive ?

Reason I ask is most examples I comes across online seem to be using a mix of all caps, mixed case, etc as well. 
It would be good if case sensitivity was not an issue foe sqlpage headers ?

**Comment by accforgithubtest** [comment]
That is awesome ! thank you so much @lovasoa
